export const BACKEND_URL = process.env.REACT_APP_BACKEND_URL;
export const UPLOAD_PHOTO_BACKEND = process.env.REACT_APP_UPLOAD_PHOTO_BACKEND;
export const UPLOAD_PHOTO_BACKEND_KEY = process.env.REACT_APP_UPLOAD_PHOTO_BACKEND_KEY;
export const ADMIN_PASSWORD = process.env.REACT_APP_ADMIN_PASSWORD;
export const FETCH_PRODUCT_LIMIT = 6;
